### ISSUE TITLE
Unable to locate package ocaml-native-compilers

### ISSUE THREAD

**Issue by longquan7** [HaxeFoundation/docker-library-haxe#3]
I want to build this 3.4/Dockerfile on arm64, but when it run step 8-->ocaml-native-compilers,there is a problem. So I want to know this image whether or not support arm64 .

**Comment by longquan7** [comment]
I think haxe is not support arm64,because I was found that ocaml-native-compilers is not support arm64 architecture at this https://packages.debian.org/jessie/ocaml-native-compilers

**Comment by andyli** [comment]
Haxe works on arm64. It's just a build issue.

You may try base on the `stretch` image (instead of `jessie`), which contains arm64 `ocaml-native-compilers`.

Another (slightly more complex) way would be changing `make OCAMLOPT=ocamlopt.opt` to just `make`. In this case, `ocaml-native-compilers` can be removed, and `ocaml` probably should be moved from buildDeps to runtime dependencies.

**Comment by longquan7** [comment]
@andyli  I'm trying to build ,thanks

**Comment by andyli** [comment]
I've enabled arm64v8 for stretch and alpine variants.
