### ISSUE TITLE
Ubuntu 18.04 image request

### ISSUE THREAD

**Issue by peterfraedrich** [HaxeFoundation/docker-library-haxe#6]
I would very much like an official Haxe image for Ubuntu 18.04 (Bionic Beaver). Are there plans to create one soon?

**Comment by andyli** [comment]
From looking at official images of other languages (python, php), the convention seems to be supporting only Debian releases but not Ubuntu, so I will keep it aligned with the others.

Given Ubuntu is based on Debian anyway, you can create a bionic image based on [our official stretch image](https://github.com/HaxeFoundation/docker-library-haxe/blob/master/3.4/stretch/Dockerfile). There are only 2 modifications required:

 * Change the `FROM` line to `FROM ubuntu:bionic`.
 * Install `wget`, `ca-certificates`, and `git` in order to fetch neko and haxe source. Since they are quite small, putting them in the "runtime dependencies" section would be fine.
