### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [HaxeFoundation/docker-library-haxe#7]
Hi,

The Haxe docker package is building and running fine at my end for ARM64v8 architecture.

Branch used to build is: Stable: latest: 
````
3.4/stretch
````

Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by lag-linaro** [comment]
+1

We have also independently verified this project on ARM64v8.

It would be great to have it `docker pull`able on our platforms.

**Comment by andyli** [comment]
Thanks for looking into it. Yes, I'm interesting in added ARM support to the images. I've a Raspberry Pi 3, but my micro sdcard is out of order so I have to buy a new one before testing the docker images with it. I would prefer having all the Linux variants available to ARM instead of just the stretch variant.

**Comment by lag-linaro** [comment]
Thanks @andyli.  You're a star!

**Comment by andyli** [comment]
The stretch variants are now available to [arm32v7](https://hub.docker.com/r/arm32v7/haxe/) and [arm64v8](https://hub.docker.com/r/arm64v8/haxe/).

I'm getting close to enabling arm support for the alpine* variants too, but it will take a bit more time.

I got some apt error for the jessie variants. I will need to see if it is easy to fix, if not, I will just keep it disabled for arm since we have the more updated stretch images anyway.

**Comment by odidev** [comment]
Thanks a lot, @andyli .
Really appreciate your support. :smiley:

**Comment by andyli** [comment]
I've enabled arm64v8 for the alpine* variants too. I'm closing this for now. :)
